services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    hostname: backend

  qdrant:
    image: qdrant/qdrant:latest
    hostname: qdrant
    ports:
      - 6333:6333
    expose:
      - 6333
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO 
